### PR TITLE
LRDOCS-9474 Code

### PR DESCRIPTION
**Pull request by mtokudome**
https://issues.liferay.com/browse/LRDOCS-9474

### CODE REVIEW

**Comment by mtokudome** [comment]
Hi @drewbrokke, I was trying to take the previous E3Q3 example and now scope the app to Company/Instance by using ConfigurationProvider. Not quite sure how to implement it. Would you be able to give me some feedback?

**Comment by drewbrokke** [comment]
Hey @mtokudome, it seems that you've created the `N2F3WebConfigurationProvider` class, but are not using it at all. Is this intentional?

**Comment by mtokudome** [comment]
@drewbrokke I'm not so clear on this part, so I would call the ConfigurationProvider class from the Portlet?

**Comment by drewbrokke** [comment]
@mtokudome yes, you would probably just make a new call to `ConfigurationProvider` with every request since each request could come from a different company, so you could be passing in a different `companyId` every time.

**Comment by mtokudome** [comment]
@drewbrokke So I ended up adding ConfigurationProvider directly to the Portlet and it appears to be working (i.e. I can set separate settings for each instance). What is the best practice for getting `companyId`? I currently have `long companyId = CompanyThreadLocal.getCompanyId();`

**Comment by mtokudome** [comment]
Now published: https://learn.liferay.com/dxp/latest/en/building-applications/core-frameworks/configuration-framework/setting-and-accessing-configurations.html

**Pull request closed without merging**
