### PR TITLE
usm 7.x | setting and accessing configurations | LRDOCS-9390

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-9390

Hi Makoto, this is looking good. I only made some minor edits (you're not obligated to keep my edits, of course). I have a bunch of comments, but I think it looks like more than it really is.

1. Liferay's Configuration Admin implementation isn't a _configuration interface_; Configuration API or Configuration Framework are more accurate. I believe Jorge Ferrer wanted us to call it the Configuration API, but I also see Configuration Framework in the existing `liferay-docs` text, so maybe ask Drew which is more technically accurate?

1. From what I understand, the `resources` folder with the code sample goes in the `article-name` folder--right now you have a resources folder at the same level as the article.

   ```bash
   CURRENT TREE
   configurable-application/
       resources/
           liferay-e3q3.zip/...
       setting-and-accessing-configurations.md
       setting-and-accessing-coinfigurations/
           images/...
   
   SHOULD BE THIS
   configurable-application/
       setting-and-accessing-configurations.md
       setting-and-accessing-coinfigurations/
           images/...
           resources/
               liferay-e3q3.zip/...
   ```

   `git mv` can solve this for you but you'll need to update the article's references to the code, likely.

1. Consider elevating the bit about the configuration `id` (in `Meta.OCD`) needing to be the fqcn of the configuration interface, perhaps to an _important_ admonition--this seems to come up pretty regularly, where someone's configuration isn't working because they failed to follow this rule.

1. Consider mentioning, in Categorizing the Configuration, that new categories can be added to system settings. I forget how you do this, but we should have docs on it (I hope).

1. The below statement reads funny to me--not wrong, but I think you can get more to the point by just saying something like, import the annotation class with 

   ```java
   import com.liferay.portal.configuration.metatype/annotations.ExtendedObjectClassDefinition;
   ```

    > The fully qualified class name of `@ExtendedObjectClassDefinition` class is `com.liferay.portal.configuration.metatype.annotations.ExtendedObjectClassDefinition`.

1. Maybe ask Jim if the `activate` method in the portlet class can be `private`. I know he wants to use `private` wherever possible, instead of the convention in portal to use `protected`. If you guys already went over this, ignore me.

1. I'd reorganize so that the categorization is the last step. This is where the read does something and then redeploys. I'd explain the stuff about reading in the portlet class and retrieving the values in the JSP first, then categorize the configuration last, redeploying. That can wrap things up. It ends a bit abruptly right now.

1. In 7.2 we we instructed readers to store the configuration in a `volatile` field, but I just noticed we didn't do that in this sample. Can you check with Drew to see if we still want that recommendation?

### CODE REVIEW

**Comment by mtokudome** [comment]
@rbohl Okay, I've implemented most of your suggestions. Thanks again for taking the time to give me feedback.

For #6, I'll check about that.

For #8, `volatile` was removed by Brian: https://github.com/brianchandotcom/liferay-learn/commit/95a75bd6e78cb7c9ece9ae1fb67a2b95a41afdad

**Comment by rbohl** [comment]
Sounds good-- feel free to close this at your leisure. 

By the way, the commit history makes it seem that you're re-implementing commits sent to you in a PR--this can make sense in some circumstances, but most of the time you want to 
1. Merge/rebase the PR (into your branch or into a new branch off of the base branch--master, mostly). Even merging it into a new branch, you'll get all your commits, plus the commits from the PR added to yours.
2. Make edits to the content in the branch, and add new commits on top.

This better preserves the git history of actual work done.

Another thing to do that will let someone investigating the history connect the dots--when a PR gets sent along, link to it from the older PRs.

Like 
superseded by https://github.com/brianchandotcom/liferay-learn/pull/199
forwarded: https://github.com/brianchandotcom/liferay-learn/pull/199

something like that.

**Comment by mtokudome** [comment]
@rbohl Yes, I should have merged in the PR. Since it was just some simple changes, I started already folding them in to my existing branch.

**Comment by rbohl** [comment]
Makes sense--just figured I'd mention it, in case there was a larger misunderstanding about workflows.

**Comment by mtokudome** [comment]
Now published: https://learn.liferay.com/dxp/latest/en/building-applications/core-frameworks/configuration-framework/setting-and-accessing-configurations.html

**Pull request closed without merging**
